# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-12-07 17:57:20
"""
import arcpy

def Task1():  # Task1

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")
    # Model Environment settings
    with arcpy.EnvManager(extent="246765.265388443 938377.187278361 260557.296761288 949658.875218475 PROJCS[\"NAD_1983_StatePlane_Massachusetts_Mainland_FIPS_2001\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",200000.0],PARAMETER[\"False_Northing\",750000.0],PARAMETER[\"Central_Meridian\",-71.5],PARAMETER[\"Standard_Parallel_1\",41.71666666666667],PARAMETER[\"Standard_Parallel_2\",42.68333333333333],PARAMETER[\"Latitude_Of_Origin\",41.0],UNIT[\"Meter\",1.0]]", outputCoordinateSystem="PROJCS[\"NAD_1983_StatePlane_Massachusetts_Mainland_FIPS_2001\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",200000.0],PARAMETER[\"False_Northing\",750000.0],PARAMETER[\"Central_Meridian\",-71.5],PARAMETER[\"Standard_Parallel_1\",41.71666666666667],PARAMETER[\"Standard_Parallel_2\",42.68333333333333],PARAMETER[\"Latitude_Of_Origin\",41.0],UNIT[\"Meter\",1.0]]"):
        wetdep_parkp1_2_ = "wetdep_parkp1"
        potential_sites = "potential_sites"

        # Process: Select Layer By Attribute (Select Layer By Attribute) (management)
        Salt_marsh, Count = arcpy.management.SelectLayerByAttribute(in_layer_or_view=wetdep_parkp1_2_, where_clause="IT_VALDESC = 'SALT MARSH'")

        # Process: XY Table To Point (XY Table To Point) (management)
        potential_sites_XYTableToPoint = "P:\\Final_Nov_24\\Final\\Final.gdb\\potential_sites_XYTableToPoint"
        arcpy.management.XYTableToPoint(in_table=potential_sites, out_feature_class=potential_sites_XYTableToPoint, x_field="STATE_X", y_field="STATE_Y", coordinate_system="PROJCS[\"NAD_1983_StatePlane_Massachusetts_Mainland_FIPS_2001\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",200000.0],PARAMETER[\"False_Northing\",750000.0],PARAMETER[\"Central_Meridian\",-71.5],PARAMETER[\"Standard_Parallel_1\",41.71666666666667],PARAMETER[\"Standard_Parallel_2\",42.68333333333333],PARAMETER[\"Latitude_Of_Origin\",41.0],UNIT[\"Meter\",1.0]];-36530900 -28803200 122610652.811951;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision")

        # Process: Pairwise Buffer (Pairwise Buffer) (analysis)
        potential_site_PairwiseBuffe = "P:\\Final_Nov_24\\Final\\Final.gdb\\potential_site_PairwiseBuffe"
        arcpy.analysis.PairwiseBuffer(in_features=potential_sites_XYTableToPoint, out_feature_class=potential_site_PairwiseBuffe, buffer_distance_or_field="500 Meters")

        # Process: Tabulate Intersection (Tabulate Intersection) (analysis)
        potential_site_TabulateInter = "P:\\Final_Nov_24\\Final\\Final.gdb\\potential_site_TabulateInter"
        arcpy.analysis.TabulateIntersection(in_zone_features=potential_site_PairwiseBuffe, zone_fields=["Sites_ID"], in_class_features=Salt_marsh, out_table=potential_site_TabulateInter, sum_fields=["AREA_ACRES"], out_units="HECTARES")

        # Process: XY Table To Point (2) (XY Table To Point) (management)
        potential_site_TabulateInter_XYTableToPoint = "P:\\Final_Nov_24\\Final\\Final.gdb\\potential_site_TabulateInter_XYTableToPoint"
        arcpy.management.XYTableToPoint(in_table=potential_site_TabulateInter, out_feature_class=potential_site_TabulateInter_XYTableToPoint, x_field="AREA", y_field="AREA", coordinate_system="PROJCS[\"NAD_1983_StatePlane_Massachusetts_Mainland_FIPS_2001\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",200000.0],PARAMETER[\"False_Northing\",750000.0],PARAMETER[\"Central_Meridian\",-71.5],PARAMETER[\"Standard_Parallel_1\",41.71666666666667],PARAMETER[\"Standard_Parallel_2\",42.68333333333333],PARAMETER[\"Latitude_Of_Origin\",41.0],UNIT[\"Meter\",1.0]];-36530900 -28803200 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(autoCommit=1000, baUseDetailedAggregation=False, cellAlignment="DEFAULT", 
                          cellSize="MAXOF", cellSizeProjectionMethod="CONVERT_UNITS", coincidentPoints="MEAN", 
                          compression="LZ77", maintainAttachments=True, maintainSpatialIndex=False, 
                          matchMultidimensionalVariable=True, nodata="NONE", outputMFlag="Same As Input", 
                          outputZFlag="Same As Input", preserveGlobalIds=False, pyramid="PYRAMIDS -1 NEAREST DEFAULT 75 NO_SKIP NO_SIPS", 
                          qualifiedFieldNames=True, randomGenerator="0 ACM599", rasterStatistics="STATISTICS 1 1", 
                          resamplingMethod="NEAREST", scratchWorkspace="P:\\Final_Nov_24\\Final\\Final.gdb", terrainMemoryUsage=False, 
                          tileSize="128 128", tinSaveVersion="CURRENT", transferDomains=False, 
                          transferGDBAttributeProperties=False, unionDimension=False, workspace="P:\\Final_Nov_24\\Final\\Final.gdb"):
        Task1()
