# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-12-08 18:45:02
"""
import arcpy

def Task4():  # Task4

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")
    potential_sites_XYTableToPoint_potential_sites_XYTableToPoint_3_ = "potential_sites_XYTableToPoint:potential_sites_XYTableToPoint"
    LTER_sites = "LTER_sites"

    # Process: XY Table To Point (XY Table To Point) (management)
    LTER_sites_XYTableToPoint = "P:\\Final_Nov_24\\Final\\Final.gdb\\LTER_sites_XYTableToPoint"
    arcpy.management.XYTableToPoint(in_table=LTER_sites, out_feature_class=LTER_sites_XYTableToPoint, x_field="STATE_X", y_field="STATE_Y", coordinate_system="PROJCS[\"NAD_1983_StatePlane_Massachusetts_Mainland_FIPS_2001\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",200000.0],PARAMETER[\"False_Northing\",750000.0],PARAMETER[\"Central_Meridian\",-71.5],PARAMETER[\"Standard_Parallel_1\",41.71666666666667],PARAMETER[\"Standard_Parallel_2\",42.68333333333333],PARAMETER[\"Latitude_Of_Origin\",41.0],UNIT[\"Meter\",1.0]];-36530900 -28803200 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision")

    # Process: Near (Near) (analysis)
    potential_sites_XYTableToPoint_potential_sites_XYTableToPoint_2_ = arcpy.analysis.Near(in_features=potential_sites_XYTableToPoint_potential_sites_XYTableToPoint_3_, near_features=[LTER_sites_XYTableToPoint], location="LOCATION", distance_unit="Meters")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="P:\\Final_Nov_24\\Final\\Final.gdb", workspace="P:\\Final_Nov_24\\Final\\Final.gdb"):
        Task4()
