# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-12-11 12:57:57
"""
import arcpy
from arcpy.ia import *
from arcpy.ia import *
from arcpy.ia import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *

def Task2():  # Task2

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("ImageAnalyst")

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")
    # Model Environment settings
    with arcpy.EnvManager(cellSize="P:\\Final\\PIE_LTER_Data\\flow_cost.img", extent="246689.79478244 938271.32063448 260649.79478244 949761.32063448 PROJCS[\"NAD_1983_StatePlane_Massachusetts_Mainland_FIPS_2001\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",200000.0],PARAMETER[\"False_Northing\",750000.0],PARAMETER[\"Central_Meridian\",-71.5],PARAMETER[\"Standard_Parallel_1\",41.71666666666667],PARAMETER[\"Standard_Parallel_2\",42.68333333333333],PARAMETER[\"Latitude_Of_Origin\",41.0],UNIT[\"Meter\",1.0]]", mask="P:\\Final_Nov_24\\Final\\..\\..\\Final\\PIE_LTER_Data\\flow_cost.img", 
                          outputCoordinateSystem="PROJCS[\"NAD_1983_StatePlane_Massachusetts_Mainland_FIPS_2001\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",200000.0],PARAMETER[\"False_Northing\",750000.0],PARAMETER[\"Central_Meridian\",-71.5],PARAMETER[\"Standard_Parallel_1\",41.71666666666667],PARAMETER[\"Standard_Parallel_2\",42.68333333333333],PARAMETER[\"Latitude_Of_Origin\",41.0],UNIT[\"Meter\",1.0]]", scratchWorkspace="P:\\Final_Nov_24\\Final\\..\\..\\Final_Nov_24\\Final", workspace="P:\\Final_Nov_24\\Final\\Final.gdb"):
        Guage_Stations_csv = "Guage Stations.csv"
        flow_cost_img = arcpy.Raster("flow_cost.img")
        flow_cost_img_2_ = arcpy.Raster("flow_cost.img")
        flow_cost_img_3_ = arcpy.Raster("flow_cost.img")
        potential_sites_XYTableToPoint_potential_sites_XYTableToPoint = "potential_sites_XYTableToPoint:potential_sites_XYTableToPoint"
        potential_sites_XYTableToPoint_potential_sites_XYTableToPoint_3_ = "potential_sites_XYTableToPoint:potential_sites_XYTableToPoint"
        potential_sites_XYTableToPoint_potential_sites_XYTableToPoint_4_ = "potential_sites_XYTableToPoint:potential_sites_XYTableToPoint"
        Final_gdb = "P:\\Final_Nov_24\\Final\\Final.gdb"
        potential_sites_XYTableToPoint_potential_sites_XYTableToPoint_5_ = "potential_sites_XYTableToPoint:potential_sites_XYTableToPoint"

        # Process: XY Table To Point (XY Table To Point) (management)
        GuageStations = "P:\\Final_Nov_24\\Final\\Final.gdb\\GuageStations"
        arcpy.management.XYTableToPoint(in_table=Guage_Stations_csv, out_feature_class=GuageStations, x_field="UTM_X", y_field="UTM_Y", coordinate_system="PROJCS[\"NAD_1983_UTM_Zone_19N\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-69.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]];-5120900 -9998100 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision")

        # Process: Select Layer By Attribute (2) (Select Layer By Attribute) (management)
        Guage_two, Count_2_ = arcpy.management.SelectLayerByAttribute(in_layer_or_view=GuageStations, where_clause="Gauge_Number = 25525")

        # Process: Select Layer By Attribute (3) (Select Layer By Attribute) (management)
        Guage_three, Count_3_ = arcpy.management.SelectLayerByAttribute(in_layer_or_view=GuageStations, where_clause="Gauge_Number = 25736")

        # Process: Select Layer By Attribute (Select Layer By Attribute) (management)
        Guage_one, Count = arcpy.management.SelectLayerByAttribute(in_layer_or_view=GuageStations, where_clause="Gauge_Number = 27708")

        # Process: Distance Accumulation (Distance Accumulation) (sa)
        Distance_Guage1 = "P:\\Final_Nov_24\\Final\\Distanc_GuageSt1.tif"
        Distance_Accumulation = Distance_Guage1
        Output_Back_Direction_Raster = ""
        Output_Source_Direction_Raster = ""
        Output_Source_Location_Raster = ""
        Distance_Guage1 = arcpy.sa.DistanceAccumulation(Guage_one, "", "", flow_cost_img, "", "BINARY 1 -30 30", "", "BINARY 1 45", Output_Back_Direction_Raster, Output_Source_Direction_Raster, Output_Source_Location_Raster, "", "", "", "", "PLANAR")
        Distance_Guage1.save(Distance_Accumulation)


        # Process: Distance Accumulation (2) (Distance Accumulation) (sa)
        Distance_Guage2 = "P:\\Final_Nov_24\\Final\\Distanc_GuageSt2.tif"
        Distance_Accumulation_2_ = Distance_Guage2
        Output_Back_Direction_Raster_2_ = ""
        Output_Source_Direction_Raster_2_ = ""
        Output_Source_Location_Raster_2_ = ""
        Distance_Guage2 = arcpy.sa.DistanceAccumulation(Guage_two, "", "", flow_cost_img_2_, "", "BINARY 1 -30 30", "", "BINARY 1 45", Output_Back_Direction_Raster_2_, Output_Source_Direction_Raster_2_, Output_Source_Location_Raster_2_, "", "", "", "", "PLANAR")
        Distance_Guage2.save(Distance_Accumulation_2_)


        # Process: Distance Accumulation (3) (Distance Accumulation) (sa)
        Distance_Guage3 = "P:\\Final_Nov_24\\Final\\Distanc_GuageSt3.tif"
        Distance_Accumulation_3_ = Distance_Guage3
        Output_Back_Direction_Raster_3_ = ""
        Output_Source_Direction_Raster_3_ = ""
        Output_Source_Location_Raster_3_ = ""
        Distance_Guage3 = arcpy.sa.DistanceAccumulation(Guage_three, "", "", flow_cost_img_3_, "", "BINARY 1 -30 30", "", "BINARY 1 45", Output_Back_Direction_Raster_3_, Output_Source_Direction_Raster_3_, Output_Source_Location_Raster_3_, "", "", "", "", "PLANAR")
        Distance_Guage3.save(Distance_Accumulation_3_)


        # Process: Reclassify (4) (Reclassify) (3d)
        Reclass_Safe_points_tif = "P:\\Final_Nov_24\\Final\\Reclass_Safe_points.tif"
        arcpy.ddd.Reclassify(in_raster=Distance_Guage1, reclass_field="VALUE", remap="0 748 NODATA;748.010000 5792.838379 1", out_raster=Reclass_Safe_points_tif)
        Reclass_Safe_points_tif = arcpy.Raster(Reclass_Safe_points_tif)

        # Process: Extract Values to Points (Extract Values to Points) (sa)
        Guage1_Safe_points_shp = "P:\\Final_Nov_24\\Final\\Guage1_Safe_points.shp"
        arcpy.sa.ExtractValuesToPoints(potential_sites_XYTableToPoint_potential_sites_XYTableToPoint, Reclass_Safe_points_tif, Guage1_Safe_points_shp, "NONE", "VALUE_ONLY")

        # Process: Reclassify (5) (Reclassify) (3d)
        Reclass_safepoints2_tif = "P:\\Final_Nov_24\\Final\\Reclass_safepoints2.tif"
        arcpy.ddd.Reclassify(in_raster=Distance_Guage2, reclass_field="VALUE", remap="0 1250 NODATA;1250 6605.396973 1", out_raster=Reclass_safepoints2_tif)
        Reclass_safepoints2_tif = arcpy.Raster(Reclass_safepoints2_tif)

        # Process: Extract Values to Points (2) (Extract Values to Points) (sa)
        Guage_2_safe_points_shp = "P:\\Final_Nov_24\\Final\\Guage_2_safe_points.shp"
        arcpy.sa.ExtractValuesToPoints(potential_sites_XYTableToPoint_potential_sites_XYTableToPoint_3_, Reclass_safepoints2_tif, Guage_2_safe_points_shp, "NONE", "VALUE_ONLY")

        # Process: Reclassify (3) (Reclassify) (3d)
        Storm_guage3_tif = "P:\\Final_Nov_24\\Final\\Reclass_Distanc3.tif"
        arcpy.ddd.Reclassify(in_raster=Distance_Guage3, reclass_field="VALUE", remap="0 450 1;450 7575.333008 NODATA", out_raster=Storm_guage3_tif)
        Storm_guage3_tif = arcpy.Raster(Storm_guage3_tif)

        # Process: Raster Calculator (3) (Raster Calculator) (ia)
        Storm_surge3_tif = "P:\\Final_Nov_24\\Final\\Storm_surge3.tif"
        Raster_Calculator_3_ = Storm_surge3_tif
        Storm_surge3_tif =  Storm_guage3_tif * Distance_Guage3
        Storm_surge3_tif.save(Raster_Calculator_3_)


        # Process: Reclassify (6) (Reclassify) (3d)
        Reclass_safepoints3_tif = "P:\\Final_Nov_24\\Final\\Reclass_safepoints3.tif"
        arcpy.ddd.Reclassify(in_raster=Distance_Guage3, reclass_field="VALUE", remap="0 450 NODATA;450 7575.333008 1", out_raster=Reclass_safepoints3_tif)
        Reclass_safepoints3_tif = arcpy.Raster(Reclass_safepoints3_tif)

        # Process: Extract Values to Points (3) (Extract Values to Points) (sa)
        Guage3_safe_points_shp = "P:\\Final_Nov_24\\Final\\Guage3_safe_points.shp"
        arcpy.sa.ExtractValuesToPoints(potential_sites_XYTableToPoint_potential_sites_XYTableToPoint_4_, Reclass_safepoints3_tif, Guage3_safe_points_shp, "NONE", "VALUE_ONLY")

        # Process: Reclassify (Reclassify) (3d)
        Storm_guage1_tif = "P:\\Final_Nov_24\\Final\\Storm_guage1.tif"
        arcpy.ddd.Reclassify(in_raster=Distance_Guage1, reclass_field="VALUE", remap="0 748 1;748 5792.838379 NODATA", out_raster=Storm_guage1_tif)
        Storm_guage1_tif = arcpy.Raster(Storm_guage1_tif)

        # Process: Raster Calculator (Raster Calculator) (ia)
        Storm_surge1_tif = "P:\\Final_Nov_24\\Final\\Storm_surge1.tif"
        Raster_Calculator = Storm_surge1_tif
        Storm_surge1_tif =  Storm_guage1_tif *  Distance_Guage1
        Storm_surge1_tif.save(Raster_Calculator)


        # Process: Reclassify (2) (Reclassify) (3d)
        Stom_guage2_tif = "P:\\Final_Nov_24\\Final\\Reclass_Distanc2.tif"
        arcpy.ddd.Reclassify(in_raster=Distance_Guage2, reclass_field="VALUE", remap="0 1250 1;1250 6605.396973 NODATA", out_raster=Stom_guage2_tif)
        Stom_guage2_tif = arcpy.Raster(Stom_guage2_tif)

        # Process: Raster Calculator (2) (Raster Calculator) (ia)
        Storm_Surge2_tif = "P:\\Final_Nov_24\\Final\\Raster2.tif"
        Raster_Calculator_2_ = Storm_Surge2_tif
        Storm_Surge2_tif =  Distance_Guage2 * Stom_guage2_tif
        Storm_Surge2_tif.save(Raster_Calculator_2_)


        # Process: Mosaic To New Raster (Mosaic To New Raster) (management)
        Combined_storm_surge_extents = arcpy.management.MosaicToNewRaster(input_rasters=[Storm_surge1_tif, Storm_Surge2_tif], output_location=Final_gdb, raster_dataset_name_with_extension="Combined_storm_surge_extents", pixel_type="32_BIT_FLOAT", number_of_bands=1, mosaic_method="MINIMUM")[0]
        Combined_storm_surge_extents = arcpy.Raster(Combined_storm_surge_extents)

        # Process: Mosaic To New Raster (2) (Mosaic To New Raster) (management)
        Combined_safe_points = arcpy.management.MosaicToNewRaster(input_rasters=[Reclass_Safe_points_tif, Reclass_safepoints2_tif, Reclass_safepoints3_tif], output_location=Final_gdb, raster_dataset_name_with_extension="Combined_safe_points", number_of_bands=Count)[0]
        Combined_safe_points = arcpy.Raster(Combined_safe_points)

        # Process: Extract Values to Points (4) (Extract Values to Points) (sa)
        safe_points_final_shp = "P:\\Final_Nov_24\\Final\\safe_points_final.shp"
        arcpy.sa.ExtractValuesToPoints(potential_sites_XYTableToPoint_potential_sites_XYTableToPoint_5_, Combined_safe_points, safe_points_final_shp, "NONE", "VALUE_ONLY")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(autoCommit=1000, baUseDetailedAggregation=False, cellAlignment="DEFAULT", 
                          cellSizeProjectionMethod="CONVERT_UNITS", coincidentPoints="MEAN", compression="LZ77", 
                          maintainAttachments=True, maintainSpatialIndex=False, matchMultidimensionalVariable=True, 
                          nodata="NONE", outputMFlag="Same As Input", outputZFlag="Same As Input", 
                          preserveGlobalIds=False, pyramid="PYRAMIDS -1 NEAREST DEFAULT 75 NO_SKIP NO_SIPS", qualifiedFieldNames=True, 
                          randomGenerator="0 ACM599", rasterStatistics="STATISTICS 1 1", resamplingMethod="NEAREST", 
                          terrainMemoryUsage=False, tileSize="128 128", tinSaveVersion="CURRENT", 
                          transferDomains=False, transferGDBAttributeProperties=False, unionDimension=False):
        Task2()
