# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-12-11 12:59:59
"""
import arcpy
from arcpy.ia import *

def Task3():  # Task3

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")
    All_sites = "potential_sites_XYTableToPoint:potential_sites_XYTableToPoint"
    N_points = "N_points"
    P_points = "P_points"

    # Process: XY Table To Point (XY Table To Point) (management)
    N_points_XYTableToPoint1 = "P:\\Final_Nov_24\\Final\\Final.gdb\\N_points_XYTableToPoint1"
    arcpy.management.XYTableToPoint(in_table=N_points, out_feature_class=N_points_XYTableToPoint1, x_field="Long", y_field="Lat", coordinate_system="GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119521E-09;0.001;0.001;IsHighPrecision")

    # Process: Project (Project) (management)
    Nitrogen_Feature_Class = "P:\\Final_Nov_24\\Final\\Final.gdb\\N_points_XYTableToPo_Project"
    arcpy.management.Project(in_dataset=N_points_XYTableToPoint1, out_dataset=Nitrogen_Feature_Class, out_coor_system="PROJCS[\"NAD_1983_StatePlane_Massachusetts_Mainland_FIPS_2001\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",200000.0],PARAMETER[\"False_Northing\",750000.0],PARAMETER[\"Central_Meridian\",-71.5],PARAMETER[\"Standard_Parallel_1\",41.71666666666667],PARAMETER[\"Standard_Parallel_2\",42.68333333333333],PARAMETER[\"Latitude_Of_Origin\",41.0],UNIT[\"Meter\",1.0]]")

    # Process: IDW (IDW) (3d)
    IDW_N_interp_values = "P:\\Final_Nov_24\\Final\\Final.gdb\\Idw_N_points1"
    with arcpy.EnvManager(cellSize="P:\\Final_Nov_24\\PIE_LTER\\PIE_LTER_Data\\flow_cost.img\\flow_cost", mask="P:\\Final_Nov_24\\PIE_LTER\\PIE_LTER_Data\\flow_cost.img\\flow_cost"):
        arcpy.ddd.Idw(in_point_features=Nitrogen_Feature_Class, z_field="N_Conc", out_raster=IDW_N_interp_values, cell_size="45.96", power=5)
        IDW_N_interp_values = arcpy.Raster(IDW_N_interp_values)

    # Process: XY Table To Point (2) (XY Table To Point) (management)
    P_points_XYTableToPoint = "P:\\Final_Nov_24\\Final\\Final.gdb\\P_points_XYTableToPoint"
    arcpy.management.XYTableToPoint(in_table=P_points, out_feature_class=P_points_XYTableToPoint, x_field="Long", y_field="Lat", coordinate_system="GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119521E-09;0.001;0.001;IsHighPrecision")

    # Process: Project (2) (Project) (management)
    Phosphorous_Feature_Class = "P:\\Final_Nov_24\\Final\\Final.gdb\\P_points_XYTableToPo_Project"
    arcpy.management.Project(in_dataset=P_points_XYTableToPoint, out_dataset=Phosphorous_Feature_Class, out_coor_system="PROJCS[\"NAD_1983_StatePlane_Massachusetts_Mainland_FIPS_2001\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",200000.0],PARAMETER[\"False_Northing\",750000.0],PARAMETER[\"Central_Meridian\",-71.5],PARAMETER[\"Standard_Parallel_1\",41.71666666666667],PARAMETER[\"Standard_Parallel_2\",42.68333333333333],PARAMETER[\"Latitude_Of_Origin\",41.0],UNIT[\"Meter\",1.0]]")

    # Process: IDW (2) (IDW) (3d)
    IDW_P_interp_values = "P:\\Final_Nov_24\\Final\\Final.gdb\\IDW_P_interp_values"
    with arcpy.EnvManager(cellSize="P:\\Final_Nov_24\\PIE_LTER\\PIE_LTER_Data\\flow_cost.img", mask="P:\\Final_Nov_24\\PIE_LTER\\PIE_LTER_Data\\flow_cost.img"):
        arcpy.ddd.Idw(in_point_features=Phosphorous_Feature_Class, z_field="P_conc", out_raster=IDW_P_interp_values)
        IDW_P_interp_values = arcpy.Raster(IDW_P_interp_values)

    # Process: Raster Calculator (Raster Calculator) (ia)
    Ratio_N_to_P = "P:\\Final_Nov_24\\Final\\Final.gdb\\Ratio_N_to_P"
    Raster_Calculator = Ratio_N_to_P
    Ratio_N_to_P =  IDW_N_interp_values / IDW_P_interp_values
    Ratio_N_to_P.save(Raster_Calculator)


    # Process: Extract Values to Points (Extract Values to Points) (sa)
    All_points = "P:\\Final_Nov_24\\Final\\Final.gdb\\Extract_potenti2"
    arcpy.sa.ExtractValuesToPoints(All_sites, Ratio_N_to_P, All_points, "NONE", "VALUE_ONLY")

    # Process: Reclassify (Reclassify) (3d)
    Reclass_UnSafe = "P:\\Final_Nov_24\\Final\\Final.gdb\\Reclass_UnSafe"
    arcpy.ddd.Reclassify(in_raster=Ratio_N_to_P, reclass_field="VALUE", remap="4.254036 12.999999 NODATA;13 18.999999 1;19 109.276955 NODATA", out_raster=Reclass_UnSafe)
    Reclass_UnSafe = arcpy.Raster(Reclass_UnSafe)

    # Process: Extract Values to Points (2) (Extract Values to Points) (sa)
    unsafe_points = "P:\\Final_Nov_24\\Final\\Final.gdb\\unsafe_points"
    arcpy.sa.ExtractValuesToPoints(All_sites, Reclass_UnSafe, unsafe_points, "NONE", "VALUE_ONLY")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(autoCommit=1000, baUseDetailedAggregation=False, cellAlignment="DEFAULT", 
                          cellSize="MAXOF", cellSizeProjectionMethod="CONVERT_UNITS", coincidentPoints="MEAN", 
                          compression="LZ77", extent="246689.79478244 938271.32063448 260649.79478244 949761.32063448 PROJCS[\"NAD_1983_StatePlane_Massachusetts_Mainland_FIPS_2001\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",200000.0],PARAMETER[\"False_Northing\",750000.0],PARAMETER[\"Central_Meridian\",-71.5],PARAMETER[\"Standard_Parallel_1\",41.71666666666667],PARAMETER[\"Standard_Parallel_2\",42.68333333333333],PARAMETER[\"Latitude_Of_Origin\",41.0],UNIT[\"Meter\",1.0]]", maintainAttachments=True, 
                          maintainSpatialIndex=False, matchMultidimensionalVariable=True, nodata="NONE", 
                          outputCoordinateSystem="PROJCS[\"NAD_1983_StatePlane_Massachusetts_Mainland_FIPS_2001\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",200000.0],PARAMETER[\"False_Northing\",750000.0],PARAMETER[\"Central_Meridian\",-71.5],PARAMETER[\"Standard_Parallel_1\",41.71666666666667],PARAMETER[\"Standard_Parallel_2\",42.68333333333333],PARAMETER[\"Latitude_Of_Origin\",41.0],UNIT[\"Meter\",1.0]]", outputMFlag="Same As Input", outputZFlag="Same As Input", 
                          preserveGlobalIds=False, pyramid="PYRAMIDS -1 NEAREST DEFAULT 75 NO_SKIP NO_SIPS", qualifiedFieldNames=True, 
                          randomGenerator="0 ACM599", rasterStatistics="STATISTICS 1 1", resamplingMethod="NEAREST", 
                          scratchWorkspace="P:\\Final_Nov_24\\Final\\Final.gdb", terrainMemoryUsage=False, tileSize="128 128", 
                          tinSaveVersion="CURRENT", transferDomains=False, transferGDBAttributeProperties=False, 
                          unionDimension=False, workspace="P:\\Final_Nov_24\\Final\\Final.gdb"):
        Task3()
